import { StyleSheet } from "react-native";

import { fontScale, scale } from "../../../lib/layout";

export const styles = StyleSheet.create({
  root: { flex: 1, flexDirection: "row", backgroundColor: "#F6F7FB" },
  main: { flex: 1 },
  mainContent: { gap: scale(0) },
  profileSection: {
    flexDirection: "row",
    backgroundColor: "#F6F7FB",
    paddingVertical: scale(40),
    paddingHorizontal: scale(60),
    gap: scale(80),
  },
  leftColumn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: scale(12),
  },
  character: { width: scale(140), height: scale(140) },
  nameRow: { flexDirection: "row", alignItems: "center", gap: scale(8) },
  nickname: { fontSize: fontScale(26), fontWeight: "800" },
  nicknameEditButton: { padding: scale(4) },
  nicknameEditIcon: { width: scale(24), height: scale(24) },
  rightColumn: {
    flex: 2,
    gap: scale(24),
    justifyContent: "center",
  },
  levelSection: { alignItems: "center" },
  levelText: { fontSize: fontScale(18), color: "#374151" },
  levelValue: {
    fontSize: fontScale(24),
    fontWeight: "800",
    color: "#111827",
  },
  typeText: { fontSize: fontScale(16), color: "#6B7280" },
  statsRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: scale(32),
  },
  statItem: { alignItems: "center", gap: scale(8) },
  statIconRow: { flexDirection: "row", alignItems: "center", gap: scale(6) },
  statIcon: { width: scale(24), height: scale(24) },
  statTitle: { fontSize: fontScale(13), color: "#6B7280" },
  statValue: {
    fontSize: fontScale(20),
    fontWeight: "800",
    color: "#111827",
    marginTop: scale(4),
  },
  planGuideWrap: { position: "relative", alignItems: "center" },
  planTooltip: {
    position: "absolute",
    top: scale(72),
    width: scale(344),
    left: "50%",
    transform: [{ translateX: scale(-213) }],
    height: scale(48),
    alignItems: "center",
    justifyContent: "center",
    padding: scale(12),
    borderRadius: scale(12),
    backgroundColor: "#212124",
    overflow: "visible",
    zIndex: 2,
  },
  planTooltipArrow: {
    position: "absolute",
    top: scale(-14),
    left: scale(204),
    width: 0,
    height: 0,
    borderLeftWidth: scale(9),
    borderRightWidth: scale(9),
    borderBottomWidth: scale(16),
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "#212124",
  },
  planTooltipText: {
    color: "#FFFFFF",
    fontSize: fontScale(16),
    lineHeight: fontScale(24),
    fontWeight: "500",
    textAlign: "center",
  },
  planTooltipStrong: { fontWeight: "700" },
  accountSection: {
    backgroundColor: "#FFFFFF",
    paddingVertical: scale(24),
    paddingHorizontal: scale(40),
  },
  sectionTitle: {
    fontSize: fontScale(20),
    fontWeight: "600",
    marginBottom: scale(16),
  },
  accountContainer: {
    borderRadius: scale(12),
    marginBottom: scale(12),
    overflow: "hidden",
  },
  accountContainerConnected: { borderWidth: 2, borderColor: "#FEE500" },
  accountContainerConnectedNaver: {
    borderWidth: 2,
    borderColor: "#03C75A",
  },
  accountContainerConnectedApple: {
    borderWidth: 2,
    borderColor: "#111827",
  },
  accountBox: {
    paddingVertical: scale(14),
    paddingHorizontal: scale(16),
  },
  kakaoBox: { backgroundColor: "#FEE500" },
  naverBox: { backgroundColor: "#03C75A" },
  appleBox: { backgroundColor: "#111827" },
  accountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  providerInfo: { flexDirection: "row", alignItems: "center", gap: scale(8) },
  providerIcon: { width: scale(18), height: scale(18) },
  providerName: { fontSize: fontScale(15), fontWeight: "700" },
  accountAction: { flexDirection: "row", alignItems: "center", gap: scale(4) },
  accountActionText: {
    fontSize: fontScale(16),
    fontWeight: "600",
    color: "#5F5F5F",
  },
  shiftIcon: { width: scale(14), height: scale(14) },
  emailBox: {
    backgroundColor: "#FFFFFF",
    paddingVertical: scale(12),
    paddingHorizontal: scale(16),
  },
  emailText: { fontSize: fontScale(13), color: "#374151" },
  naverText: { color: "#FFFFFF" },
  appleText: { color: "#FFFFFF" },
  appleProviderIcon: {
    color: "#FFFFFF",
    fontSize: fontScale(16),
    fontWeight: "700",
    width: scale(18),
    textAlign: "center",
  },
  withdrawButton: { marginTop: scale(16) },
  withdrawText: { fontSize: fontScale(13), color: "#000000" },
});
