import { Platform, StyleSheet } from "react-native";
import { fontScale, scale } from "../../lib/layout";
import { BG, BORDER, CARD, HIGHLIGHT_BG, MUTED } from "./scaffoldingConstants";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: BG,
    paddingHorizontal: scale(18),
    paddingTop: scale(16),
    paddingBottom: scale(16),
    gap: scale(12),
  },
  center: { justifyContent: "center", alignItems: "center" },

  loadingText: { color: MUTED, fontSize: fontScale(12), fontWeight: "700" },

  errorTitle: {
    color: "#111827",
    fontSize: fontScale(16),
    fontWeight: "900",
    marginBottom: scale(8),
  },
  errorDesc: {
    color: MUTED,
    fontSize: fontScale(12),
    fontWeight: "700",
    textAlign: "center",
    marginBottom: scale(16),
  },
  retryBtn: {
    width: "100%",
    maxWidth: scale(320),
    height: scale(48),
    borderRadius: scale(14),
    backgroundColor: "#5E82FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: scale(10),
  },
  retryBtnText: {
    color: "#FFFFFF",
    fontSize: fontScale(12),
    fontWeight: "900",
  },
  backOnlyBtn: {
    width: "100%",
    maxWidth: scale(320),
    height: scale(48),
    borderRadius: scale(14),
    backgroundColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  backOnlyBtnText: {
    color: "#111827",
    fontSize: fontScale(12),
    fontWeight: "900",
  },

  content: { flex: 1, flexDirection: "row", gap: scale(12) },
  pageIndicatorWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: scale(8),
    alignItems: "center",
    justifyContent: "center",
  },
  pageIndicatorText: {
    color: "#6B7280",
    fontSize: fontScale(14),
    fontWeight: "900",
  },

  leftCard: {
    width: scale(170),
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: scale(16),
    paddingHorizontal: scale(12),
    paddingVertical: scale(12),
    gap: scale(12),
    justifyContent: "flex-start",
  },

  buttonGroup: {
    marginTop: "auto",
    gap: scale(12),
  },

  helpBox: {
    borderRadius: scale(14),
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D6DBFF",
    overflow: "hidden",
  },
  helpHeader: {
    backgroundColor: "#EEF1FF",
    paddingHorizontal: scale(12),
    paddingVertical: scale(12),
    alignItems: "center",
    justifyContent: "center",
  },
  helpBody: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: scale(12),
    paddingVertical: scale(12),
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 1,
    borderTopColor: "#D6DBFF",
  },
  helpTitle: {
    fontSize: fontScale(13),
    fontWeight: "900",
    color: "#111827",
    textAlign: "center",
  },
  helpDesc: {
    fontSize: fontScale(11),
    fontWeight: "700",
    color: MUTED,
    lineHeight: fontScale(16),
    textAlign: "center",
  },
  helpDescBottom: { marginTop: scale(2) },

  rightCard: {
    flex: 1,
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: scale(16),
    overflow: "hidden",
    position: "relative",
  },
  textContainer: { paddingHorizontal: scale(14), paddingVertical: scale(14) },
  pageList: { gap: scale(14) },
  pageCard: {
    gap: scale(8),
  },
  pageCardTitle: {
    fontSize: fontScale(12),
    lineHeight: fontScale(18),
    fontWeight: "700",
    color: "#6B7280",
  },
  pageSheet: {
    padding: scale(14),
    borderRadius: scale(14),
    backgroundColor: "#F8FAFF",
    borderWidth: 1,
    borderColor: "#E3E8F8",
    gap: scale(12),
  },
  pageCanvas: {
    position: "relative",
    width: "100%",
    borderRadius: scale(12),
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8ECF8",
    overflow: "hidden",
  },
  layoutBlock: {
    position: "absolute",
    paddingHorizontal: scale(3),
    paddingVertical: scale(2),
    overflow: "visible",
  },
  structuredBlockText: {
    color: "#111827",
    fontWeight: "500",
    padding: 0,
    margin: 0,
  },
  structuredKeywordBox: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
  },
  structuredKeywordInlineBox: {
    alignSelf: "flex-start",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
  },
  structuredKeywordBoxDefault: {
    backgroundColor: HIGHLIGHT_BG,
    borderRadius: scale(2),
  },
  structuredKeywordBoxSelected: {
    backgroundColor: "rgba(199, 207, 255, 0.55)",
  },
  structuredKeywordInputBox: {
    backgroundColor: HIGHLIGHT_BG,
    borderRadius: scale(2),
  },
  structuredKeywordInputBoxActive: {
    borderColor: "#5E82FF",
  },
  layoutBlockFlow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  coordinatePage: {
    width: "100%",
    borderRadius: scale(12),
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8ECF8",
    paddingHorizontal: scale(16),
    paddingVertical: scale(16),
  },
  coordinateColumns: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: scale(18),
  },
  coordinateColumn: {
    flex: 1,
    minWidth: 0,
  },
  coordinateLine: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
  },
  coordinateWord: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
  },
  pageTableWrap: {
    gap: scale(6),
  },
  pageTableTitle: {
    fontSize: fontScale(12),
    lineHeight: fontScale(18),
    fontWeight: "700",
    color: "#6B7280",
  },
  pageTable: {
    borderWidth: 1,
    borderColor: "#D8DEEF",
    borderRadius: scale(10),
    overflow: "hidden",
  },
  pageTableRow: {
    flexDirection: "row",
  },
  pageTableCell: {
    minWidth: scale(88),
    maxWidth: scale(240),
    paddingHorizontal: scale(10),
    paddingVertical: scale(8),
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#D8DEEF",
    backgroundColor: "#FFFFFF",
  },
  pageTableHeaderCell: {
    backgroundColor: "#EEF2FF",
  },
  pageTableCellFlow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
  },
  flow: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start" },
  newline: { width: "100%", height: fontScale(14) },
  bodyText: {
    fontSize: fontScale(14),
    lineHeight: fontScale(22),
    fontWeight: "600",
    color: "#111827",
  },
  compactBodyText: { fontWeight: "500", color: "#1F2937" },

  wordPill: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: scale(4),
    marginVertical: 0,
  },
  compactWordPill: { marginVertical: 0, minHeight: 0 },
  blankTokenSpacing: {
    marginHorizontal: scale(3),
    paddingHorizontal: scale(4),
  },
  wordText: {
    fontSize: fontScale(13),
    lineHeight: fontScale(20),
    fontWeight: "600",
    color: "#111827",
  },
  compactWordText: { fontWeight: "500" },

  blankBox: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: scale(4),
    marginVertical: 0,
    justifyContent: "center",
  },
  blankBoxBase: {
    borderWidth: 2,
    borderColor: "transparent",
    position: "relative",
    overflow: "hidden",
  },
  blankBoxActive: { borderColor: "#5E82FF" },
  blankInputOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    overflow: "hidden",
  },
  blankAnswerScroll: {
    ...StyleSheet.absoluteFillObject,
  },
  blankAnswerScrollContent: {
    alignItems: "center",
  },
  blankInput: {
    ...StyleSheet.absoluteFillObject,
    height: "100%",
    minHeight: 0,
    padding: 0,
    paddingVertical: 0,
    margin: 0,
    fontSize: fontScale(13),
    fontWeight: "600",
    color: "#111827",
    lineHeight: fontScale(20),
    includeFontPadding: false,
    textAlignVertical: "center",
    borderWidth: 0,
    ...(Platform.OS === "web"
      ? { outlineStyle: "solid", outlineWidth: 0 }
      : {}),
  },
  blankHiddenInput: {
    opacity: 0,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: scale(18),
  },
  modalCard: {
    width: "100%",
    maxWidth: scale(430),
    backgroundColor: "#FFFFFF",
    borderRadius: scale(16),
    paddingHorizontal: scale(18),
    paddingTop: scale(18),
    paddingBottom: scale(16),
  },
  modalClose: {
    position: "absolute",
    right: scale(12),
    top: scale(10),
    width: scale(32),
    height: scale(32),
    borderRadius: scale(16),
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseText: {
    fontSize: fontScale(22),
    fontWeight: "900",
    color: "#9CA3AF",
  },
  modalWord: {
    fontSize: fontScale(20),
    fontWeight: "900",
    color: "#111827",
    marginBottom: scale(8),
  },
  modalLong: {
    fontSize: fontScale(12),
    fontWeight: "700",
    color: "#111827",
    lineHeight: fontScale(18),
  },

  hintModalOverlay: {
    flex: 1,
    backgroundColor: "transparent",
    paddingHorizontal: scale(18),
  },

  // 설명
  popupOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },
  popupBackdrop: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.25)",
    paddingHorizontal: scale(18),
  },
  popupCard: {
    width: scale(300),
    borderRadius: scale(20),
    backgroundColor: "#FFFFFF",
    paddingVertical: scale(22),
    paddingHorizontal: scale(18),
    alignItems: "center",
    elevation: 6,
  },
  popupTitle: {
    fontSize: fontScale(18),
    fontWeight: "800",
    color: "#111827",
    marginBottom: scale(10),
    textAlign: "center",
  },
  popupMessage: {
    fontSize: fontScale(14),
    color: "#111827",
    marginBottom: scale(16),
    textAlign: "center",
    lineHeight: fontScale(20),
  },
  popupConfirmBtn: {
    width: "100%",
    height: scale(44),
    borderRadius: scale(12),
    backgroundColor: "#5E82FF",
    alignItems: "center",
    justifyContent: "center",
  },
  popupConfirmText: {
    color: "#FFFFFF",
    fontSize: fontScale(14),
    fontWeight: "800",
  },
  hintBalloonContainer: { alignItems: "center", justifyContent: "center" },
  hintBalloonBubble: {
    paddingHorizontal: scale(14),
    paddingVertical: scale(8),
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  hintContent: {
    flexDirection: "row",
    gap: scale(8),
    justifyContent: "center",
  },
  hintButton: {
    paddingHorizontal: scale(10),
    paddingVertical: scale(6),
    borderRadius: scale(6),
    minWidth: scale(42),
    alignItems: "center",
    justifyContent: "center",
  },
  hintButtonActive: { backgroundColor: "#5E82FF" },
  hintButtonInactive: { backgroundColor: "#E5E7EB" },
  hintButtonText: { fontSize: fontScale(13), fontWeight: "700" },
  hintButtonTextActive: { color: "#FFFFFF" },
  hintButtonTextInactive: { color: "#9CA3AF" },
  dragSelectionBox: {
    position: "absolute",
    borderWidth: 1,
    borderColor: "#5E82FF",
    backgroundColor: "rgba(94,130,255,0.15)",
    borderRadius: scale(4),
  },
  dragConfirmBtn: {
    position: "absolute",
    paddingHorizontal: scale(10),
    paddingVertical: scale(6),
    backgroundColor: "#111827",
    borderRadius: scale(10),
    zIndex: 5,
  },
  dragConfirmText: {
    color: "#FFFFFF",
    fontSize: fontScale(11),
    fontWeight: "800",
  },
});
