import { Dimensions, StyleSheet } from "react-native";

import { fontScale, scale } from "../../../../lib/layout";

const BACKGROUND_COLOR = "#F6F7FB";
const MASK_COLOR = "rgba(0,0,0,0.35)";
const { height: windowHeight } = Dimensions.get("window");
const previewHeight = Math.min(scale(380), windowHeight * 0.45);

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: BACKGROUND_COLOR,
  },
  centerWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: scale(16),
    paddingTop: scale(44),
    paddingBottom: scale(16),
  },
  topContent: {
    width: "100%",
    alignItems: "center",
  },
  guide: {
    textAlign: "center",
    fontSize: fontScale(18),
    fontWeight: "800",
    color: "#111827",
    marginBottom: scale(10),
    lineHeight: fontScale(26),
  },
  guideSubtext: {
    textAlign: "center",
    fontSize: fontScale(13),
    fontWeight: "600",
    color: "#4B5563",
    marginBottom: scale(18),
  },
  usageSlot: {
    width: "100%",
    minHeight: scale(40),
    alignItems: "center",
    justifyContent: "flex-start",
  },
  usageChip: {
    alignSelf: "center",
    backgroundColor: "#EEF2FF",
    paddingHorizontal: scale(12),
    paddingVertical: scale(6),
    borderRadius: scale(999),
  },
  usageText: {
    color: "#4338CA",
    fontSize: fontScale(12),
    fontWeight: "700",
  },
  usageErrorText: {
    color: "#EF4444",
    fontSize: fontScale(11),
    fontWeight: "700",
    marginBottom: scale(8),
    textAlign: "center",
  },
  modalOverlay: {
    backgroundColor: "rgba(15, 23, 42, 0.32)",
  },
  modalBox: {
    width: "100%",
    maxWidth: scale(340),
    borderRadius: scale(20),
    paddingHorizontal: scale(22),
    paddingVertical: scale(22),
    alignItems: "center",
  },
  modalTitle: {
    fontSize: fontScale(20),
    fontWeight: "900",
    color: "#111827",
    marginBottom: scale(12),
    textAlign: "center",
  },
  modalMessage: {
    fontSize: fontScale(14),
    fontWeight: "700",
    color: "#4B5563",
    lineHeight: fontScale(20),
    textAlign: "center",
  },
  modalPrimaryButton: {
    marginTop: scale(18),
    width: "100%",
    height: scale(48),
    borderRadius: scale(14),
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
  },
  modalPrimaryText: {
    fontSize: fontScale(15),
    fontWeight: "900",
    color: "#FFFFFF",
  },
  categorySection: {
    width: "100%",
    maxWidth: scale(550),
    marginBottom: scale(20),
  },
  categoryLabel: {
    color: "#111827",
    fontSize: fontScale(13),
    fontWeight: "800",
    marginBottom: scale(8),
  },
  categoryRow: {
    minHeight: scale(42),
    alignItems: "center",
    gap: scale(8),
    paddingRight: scale(4),
  },
  categoryButton: {
    minHeight: scale(38),
    paddingHorizontal: scale(14),
    paddingVertical: scale(9),
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: scale(19),
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  categoryButtonActive: {
    borderColor: "#5E82FF",
    backgroundColor: "#EEF2FF",
  },
  categoryButtonText: {
    fontSize: fontScale(14),
    fontWeight: "800",
    color: "#111827",
  },
  categoryButtonTextActive: {
    color: "#4338CA",
  },
  categoryAddButton: {
    width: scale(38),
    height: scale(38),
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: scale(19),
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  categoryAddText: {
    color: "#4B5563",
    fontSize: fontScale(22),
    fontWeight: "800",
    lineHeight: fontScale(24),
  },
  categoryInputWrap: {
    height: scale(38),
    width: scale(86),
    flexDirection: "row",
    alignItems: "center",
    borderRadius: scale(19),
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  categoryInput: {
    flex: 1,
    paddingHorizontal: scale(14),
    paddingVertical: 0,
    color: "#111827",
    fontSize: fontScale(14),
    fontWeight: "800",
  },
  categoryModalBox: {
    maxWidth: scale(340),
  },
  categoryModalContent: {
    padding: scale(20),
    gap: scale(16),
  },
  categoryModalInput: {
    width: "100%",
    minHeight: scale(46),
    paddingHorizontal: scale(14),
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: scale(12),
    color: "#111827",
    fontSize: fontScale(15),
    fontWeight: "800",
    backgroundColor: "#FFFFFF",
  },
  categoryModalButtons: {
    flexDirection: "row",
    gap: scale(10),
  },
  categoryModalButton: {
    flex: 1,
    minHeight: scale(44),
    borderRadius: scale(12),
    alignItems: "center",
    justifyContent: "center",
  },
  categoryDeleteButton: {
    backgroundColor: "#FEF2F2",
  },
  categorySaveButton: {
    backgroundColor: "#5E82FF",
  },
  categoryDeleteText: {
    color: "#EF4444",
    fontSize: fontScale(14),
    fontWeight: "900",
  },
  categorySaveText: {
    color: "#FFFFFF",
    fontSize: fontScale(14),
    fontWeight: "900",
  },
  previewWrap: {
    width: "100%",
    maxWidth: scale(550),
    height: previewHeight,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: scale(12),
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  previewInner: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  previewImage: {
    width: "100%",
    height: "100%",
  },
  fileCard: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: scale(24),
    backgroundColor: "#F8FAFC",
  },
  fileExt: {
    color: "#111827",
    fontSize: fontScale(28),
    fontWeight: "900",
    marginBottom: scale(10),
  },
  fileName: {
    color: "#1F2937",
    fontSize: fontScale(15),
    fontWeight: "700",
    textAlign: "center",
    marginBottom: scale(10),
  },
  fileHint: {
    color: "#6B7280",
    fontSize: fontScale(12),
    textAlign: "center",
  },
  empty: {
    width: "100%",
    height: "100%",
    borderRadius: scale(16),
    backgroundColor: "rgba(0,0,0,0.04)",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyText: {
    color: "#9CA3AF",
    fontSize: fontScale(13),
    fontWeight: "700",
  },
  cropArea: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
  },
  maskTop: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    backgroundColor: MASK_COLOR,
  },
  maskBottom: {
    position: "absolute",
    left: 0,
    width: "100%",
    backgroundColor: MASK_COLOR,
  },
  maskLeft: {
    position: "absolute",
    left: 0,
    backgroundColor: MASK_COLOR,
  },
  maskRight: {
    position: "absolute",
    backgroundColor: MASK_COLOR,
  },
  cropFrame: {
    position: "absolute",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
  },
  cropMoveArea: {
    position: "absolute",
    backgroundColor: "transparent",
  },
  cropCornerTL: {
    position: "absolute",
    left: 6,
    top: 6,
    width: 18,
    height: 18,
    borderLeftWidth: 2,
    borderTopWidth: 2,
    borderColor: "#FFFFFF",
  },
  cropCornerTR: {
    position: "absolute",
    right: 6,
    top: 6,
    width: 18,
    height: 18,
    borderRightWidth: 2,
    borderTopWidth: 2,
    borderColor: "#FFFFFF",
  },
  cropCornerBL: {
    position: "absolute",
    left: 6,
    bottom: 6,
    width: 18,
    height: 18,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#FFFFFF",
  },
  cropCornerBR: {
    position: "absolute",
    right: 6,
    bottom: 6,
    width: 18,
    height: 18,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#FFFFFF",
  },
  handle: {
    position: "absolute",
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    cursor: "pointer",
    zIndex: 10,
  },
  handleDot: {
    width: 12,
    height: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  rotateRow: {
    width: "100%",
    maxWidth: scale(550),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: scale(14),
    paddingHorizontal: scale(8),
    marginTop: scale(12),
    marginBottom: scale(12),
  },
  rotateButtonSpacer: {
    width: scale(48),
    height: scale(48),
  },
  rotateBtnLeft: {
    width: scale(48),
    height: scale(48),
    alignItems: "center",
    justifyContent: "center",
  },
  rotateBtnRight: {
    width: scale(48),
    height: scale(48),
    alignItems: "center",
    justifyContent: "center",
  },
  rotateIcon: {
    width: scale(28),
    height: scale(28),
    tintColor: "#1F2937",
  },
  rotateRight: {
    transform: [{ scaleX: -1 }],
  },
  recentWrap: {
    flex: 1,
    maxWidth: scale(390),
    height: scale(90),
    alignItems: "center",
    justifyContent: "center",
  },
  recentRow: {
    alignItems: "center",
    justifyContent: "flex-start",
    gap: scale(16),
    paddingHorizontal: scale(8),
  },
  thumbBtn: {
    borderRadius: scale(14),
    borderWidth: 3,
    borderColor: "#E5E7EB",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  thumbBtnActive: {
    borderColor: "#5E82FF",
    shadowColor: "#5E82FF",
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  thumb: {
    width: scale(70),
    height: scale(70),
    borderRadius: scale(11),
  },
  fileThumb: {
    width: scale(70),
    height: scale(70),
    borderRadius: scale(11),
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: scale(4),
    backgroundColor: "#F8FAFC",
  },
  fileThumbExt: {
    color: "#111827",
    fontSize: fontScale(10),
    fontWeight: "900",
  },
  fileThumbName: {
    color: "#4B5563",
    fontSize: fontScale(8),
    fontWeight: "700",
    textAlign: "center",
    marginTop: scale(2),
  },
  fab: {
    position: "absolute",
    right: scale(28),
    bottom: scale(28),
    width: scale(128),
    height: scale(128),
    borderRadius: 0,
    zIndex: 10,
    elevation: 5,
    shadowColor: "#5E82FF",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  fabImage: {
    width: "100%",
    height: "100%",
  },
});
