import { StyleSheet } from "react-native";

import { fontScale, scale } from "../../../../lib/layout";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#0B0F1A" },
  cameraWrap: { flex: 1 },
  cameraFill: StyleSheet.absoluteFillObject,
  center: { justifyContent: "center", alignItems: "center" },
  permissionText: {
    fontSize: scale(18),
    color: "#fff",
    marginBottom: scale(12),
  },
  primaryBtn: {
    paddingHorizontal: scale(14),
    paddingVertical: scale(10),
    borderRadius: scale(14),
    backgroundColor: "#5E82FF",
  },
  secondaryBtn: {
    marginTop: scale(10),
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  primaryBtnText: {
    color: "#fff",
    fontSize: fontScale(25),
    fontWeight: "800",
    marginVertical: scale(5),
    marginHorizontal: scale(5),
  },
  topBar: {
    position: "absolute",
    left: scale(16),
    right: scale(16),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 5,
  },
  topTitle: { color: "#fff", fontSize: fontScale(16), fontWeight: "800" },
  topBarSpacer: { width: scale(28) },
  backChip: {
    width: scale(28),
    height: scale(28),
    borderRadius: scale(14),
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  backIcon: {
    width: scale(18),
    height: scale(18),
    transform: [{ rotate: "180deg" }],
  },
  rightButtons: {
    position: "absolute",
    right: scale(16),
    top: scale(140),
    bottom: scale(160),
    alignItems: "center",
    justifyContent: "center",
    gap: scale(10),
    zIndex: 5,
  },
  timerBtnGroup: { alignItems: "center", gap: scale(2) },
  iconBtn: {
    width: scale(48),
    height: scale(48),
    alignItems: "center",
    justifyContent: "center",
  },
  timerLabel: {
    color: "#fff",
    fontSize: fontScale(10),
    fontWeight: "600",
  },
  shutterOuter: {
    width: scale(70),
    height: scale(70),
    borderRadius: scale(35),
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: scale(8),
  },
  shutterImage: { width: scale(60), height: scale(60) },
  finishBtn: {
    width: scale(48),
    height: scale(48),
    borderRadius: scale(24),
    alignItems: "center",
    justifyContent: "center",
    marginTop: scale(8),
  },
  finishImage: { width: scale(60), height: scale(60) },
  thumbnailContainer: {
    width: scale(48),
    height: scale(48),
    alignItems: "center",
    justifyContent: "center",
  },
  thumbnailImage: {
    width: scale(44),
    height: scale(44),
    borderRadius: scale(8),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  thumbnailAnchor: {
    width: scale(48),
    height: scale(48),
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  countOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.35)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 6,
  },
  countText: { color: "#fff", fontSize: fontScale(72), fontWeight: "900" },
});
