import { StyleSheet } from "react-native";

import { fontScale, scale } from "../../../lib/layout";

const CARD_SHADOW = {
  shadowColor: "#0F172A",
  shadowOpacity: 0.1,
  shadowRadius: 18,
  shadowOffset: { width: 0, height: 8 },
  elevation: 5,
};

export const styles = StyleSheet.create({
  root: { flex: 1, flexDirection: "row", backgroundColor: "#F3F4F6" },
  main: { flex: 1 },
  mainContent: { paddingHorizontal: 18, paddingVertical: 16 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: scale(16),
  },
  welcome: {
    fontSize: fontScale(30),
    fontWeight: "800",
    marginTop: scale(10),
    marginBottom: scale(8),
    marginHorizontal: scale(8),
  },
  alarmButton: { padding: scale(4) },
  alarmIcon: {
    width: scale(24),
    height: scale(24),
    tintColor: "#9CA3AF",
  },
  contentRow: {
    flexDirection: "row",
    gap: 14,
    alignItems: "flex-start",
  },
  leftColumn: { flex: 0.97 },
  rightColumn: { flex: 1.03, gap: 8 },
  rightBottomCard: { marginTop: 4 },
  levelText: {
    fontSize: fontScale(16),
    fontWeight: "600",
    marginBottom: scale(8),
  },
  levelLabel: { color: "#000000" },
  levelValue: {
    fontSize: fontScale(20),
    color: "#000000",
    fontWeight: "800",
  },
  characterWrapper: {
    width: "100%",
    alignItems: "center",
    marginBottom: scale(2),
  },
  characterImage: { marginBottom: scale(2), marginTop: scale(2) },
  todayButton: {
    borderRadius: scale(16),
    paddingVertical: scale(12),
    backgroundColor: "#5E82FF",
    alignItems: "center",
  },
  todayButtonInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: scale(6),
  },
  todayButtonIcon: {
    width: scale(24),
    height: scale(24),
    tintColor: "#FFFFFF",
  },
  todayButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: fontScale(24),
  },
  smallTitle: {
    fontSize: fontScale(25),
    fontWeight: "500",
    marginBottom: -4,
  },
  lineGraphContainer: {
    minHeight: scale(138),
    marginTop: scale(0),
    marginBottom: scale(0),
    justifyContent: "flex-start",
    alignItems: "stretch",
  },
  lineChartWrapper: { width: "100%", alignItems: "stretch" },
  lineChartContainer: {
    width: "100%",
    height: scale(135),
    position: "relative",
    marginBottom: scale(2),
  },
  graphBackground: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
  },
  svgOverlay: { position: "absolute", top: 0, left: 0 },
  graphStatsTextContainer: {
    alignItems: "flex-start",
    marginTop: scale(-2),
    paddingLeft: scale(8),
    paddingBottom: scale(4),
    width: "100%",
    includeFontPadding: false,
  },
  graphStatsLabel: {
    fontSize: fontScale(15),
    color: "#4B5563",
    fontWeight: "800",
    marginBottom: scale(4),
  },
  graphPlaceholder: {
    fontSize: fontScale(11),
    color: "#9CA3AF",
    textAlign: "center",
    paddingVertical: scale(20),
  },
  streakRow: { flexDirection: "row", alignItems: "center" },
  fireImage: {
    width: scale(80),
    height: scale(80),
    tintColor: "#E5E7EB",
    marginRight: scale(14),
    marginBottom: scale(4),
    marginTop: scale(4),
  },
  fireImageActive: { tintColor: "#F973A6" },
  streakContent: { flex: 1 },
  streakTitle: {
    fontSize: fontScale(23),
    fontWeight: "700",
    marginBottom: scale(25),
  },
  streakStrong: { fontWeight: "800", fontSize: fontScale(18) },
  weekRow: { flexDirection: "row", justifyContent: "space-between" },
  weekItem: { alignItems: "center" },
  weekCircle: {
    width: scale(28),
    height: scale(28),
    borderRadius: scale(14),
    backgroundColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  weekCircleChecked: { backgroundColor: "#FED7E2" },
  weekLabel: { fontSize: fontScale(16), color: "#4B5563" },
  weekLabelChecked: { color: "#EC4899", fontWeight: "700" },
  todayTriangle: {
    marginTop: 4,
    width: 0,
    height: 0,
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 7,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "#3B82F6",
  },
  leagueCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 16,
    ...CARD_SHADOW,
    marginBottom: scale(12),
  },
  leagueTitle: {
    fontSize: fontScale(20),
    fontWeight: "400",
    marginBottom: fontScale(25),
    marginHorizontal: scale(4),
    marginTop: scale(8),
  },
  leagueRow: { flexDirection: "row", alignItems: "center" },
  leagueTrophy: {
    width: scale(100),
    height: scale(100),
    marginRight: scale(14),
    marginBottom: scale(8),
  },
  leagueMainText: {
    fontSize: fontScale(25),
    fontWeight: "500",
    marginBottom: 6,
  },
  leagueRank: { fontSize: fontScale(30), fontWeight: "700" },
  leagueSubText: {
    fontSize: fontScale(15),
    fontWeight: "600",
    color: "#84858C",
    marginTop: scale(7),
  },
  leagueArrowImage: {
    width: scale(30),
    height: scale(30),
    tintColor: "#9CA3AF",
    marginLeft: 8,
  },
  goalCard: { gap: 12 },
  goalCardTitle: {
    fontSize: fontScale(25),
    fontWeight: "500",
    color: "#1F2937",
    marginTop: scale(8),
    marginBottom: scale(20),
    marginHorizontal: scale(8),
  },
  goalInlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: scale(8),
    marginBottom: scale(18),
  },
  goalItemLabel: {
    fontSize: fontScale(18),
    fontWeight: "600",
    color: "#4B5563",
    minWidth: scale(75),
    marginHorizontal: scale(8),
    marginBottom: scale(4),
  },
  goalProgressBarContainer: {
    flex: 1,
    height: scale(37),
    backgroundColor: "#E5E7EB",
    borderRadius: scale(8),
    overflow: "visible",
    position: "relative",
    justifyContent: "center",
  },
  goalProgressBar: { height: "100%", borderRadius: scale(10) },
  goalValueOverlay: {
    position: "absolute",
    right: scale(10),
    fontSize: fontScale(20),
    fontWeight: "800",
    color: "#FFFFFF",
  },
  goalHighlight: {
    fontSize: fontScale(24),
    fontWeight: "700",
    color: "#5E82FF",
    marginBottom: scale(24),
    marginHorizontal: scale(8),
    textAlign: "left",
  },
});
